// <auto-generated />
namespace Inventory.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class F23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(F23));
        
        string IMigrationMetadata.Id
        {
            get { return "201901020322169_F23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
